# Generated by Django 4.1.7 on 2023-03-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_homequestions_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homequestions',
            name='id',
            field=models.CharField(editable=False, max_length=3, primary_key=True, serialize=False),
        ),
    ]
