# Generated by Django 4.1.7 on 2023-03-03 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_alter_homequestions_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='GeneralUser',
        ),
    ]
