# Generated by Django 4.1.7 on 2023-03-03 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_user_generaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='base.room'),
        ),
    ]
