# Generated by Django 4.1.7 on 2023-03-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_option_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='score',
        ),
    ]
